### ISSUE TITLE
Can´t configure .exe path ..

### ISSUE THREAD

**Issue by MacSass** [ctreadw6/InfinittonWPF#20]
When I pull over the exe icon onto the grid and then click the icon in the grid one the configuration options are shown on the right.
I guess the icon behind the path should pop up a file selection dialog - but for me this does not work,
When I click it, nothing happens...

When I add a title to the .exe configuration and then click save, the app crashes ...

Regards - MacSass

**Comment by ctreadw6** [comment]
Just found the issue with the crash when adding a title and it will be fixed in the next commit. 
Currently the path is just a textbox where you can enter/paste the path to the file. I plan on adding a file selection dialog for the path.

For the icon itself - When you click save after entering a new path, the program will try to extract the icon from the exe. If it cannot, you should be able to drop an image file onto the button to replace it. I plan on adding a more intuitive way to replace the icon.

**Comment by MacSass** [comment]
Ah, I see - I guess the crash is caused by the fact that I did not have a valid path configured, as I did not see the dialogue working and did not think of manually pasting a path.
For dummies :-) it might makes sense to check the path is valid before executing it - but that is low priority, I guess ...
Thanks MacSass
